# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_(self):
    # Test name: 메시지 발송 테스트
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://center-pf.kakao.com/")
    # 2 | setWindowSize | 1012x824 | 
    self.driver.set_window_size(1012, 824)
    # 3 | click | css=.tit_invite | 
    self.driver.find_element(By.CSS_SELECTOR, ".tit_invite").click()
    # 4 | click | linkText=1:1채팅1 | 
    self.driver.find_element(By.LINK_TEXT, "1:1채팅1").click()
    # 5 | click | linkText=채팅 목록 | 
    self.driver.find_element(By.LINK_TEXT, "채팅 목록").click()
    # 6 | click | name=keyword | 
    self.driver.find_element(By.NAME, "keyword").click()
    # 7 | type | name=keyword | 이범각
    self.driver.find_element(By.NAME, "keyword").send_keys("이범각")
    # 8 | sendKeys | name=keyword | ${KEY_ENTER}
    self.driver.find_element(By.NAME, "keyword").send_keys(Keys.ENTER)
    # 9 | click | css=.txt_info:nth-child(1) | 
    self.vars["window_handles"] = self.driver.window_handles
    # 10 | storeWindowHandle | root | 
    self.driver.find_element(By.CSS_SELECTOR, ".txt_info:nth-child(1)").click()
    # 11 | selectWindow | handle=${win1945} | 
    self.vars["win1945"] = self.wait_for_window(2000)
    # 12 | close |  | 
    self.vars["root"] = self.driver.current_window_handle
    # 13 | selectWindow | handle=${root} | 
    self.driver.switch_to.window(self.vars["win1945"])
    # 14 | click | name=keyword | 
    self.driver.close()
    # 15 | click | css=.head_search | 
    self.driver.switch_to.window(self.vars["root"])
    # 16 | type | name=keyword | 이시은
    self.driver.find_element(By.NAME, "keyword").click()
    # 17 | sendKeys | name=keyword | ${KEY_ENTER}
    self.driver.find_element(By.CSS_SELECTOR, ".head_search").click()
    # 18 | click | css=span > .emph_g | 
    self.driver.find_element(By.NAME, "keyword").send_keys("이시은")
    # 19 | selectWindow | handle=${win2428} | 
    self.driver.find_element(By.NAME, "keyword").send_keys(Keys.ENTER)
    # 20 | click | id=chatWrite | 
    self.vars["window_handles"] = self.driver.window_handles
    # 21 | runScript | window.scrollTo(0,0) | 
    self.driver.find_element(By.CSS_SELECTOR, "span > .emph_g").click()
    # 22 | mouseOver | css=.txt_memo | 
    self.vars["win2428"] = self.wait_for_window(2000)
    # 23 | close |  | 
    self.driver.switch_to.window(self.vars["win2428"])
    # 24 | selectWindow | handle=${root} | 
    self.driver.find_element(By.ID, "chatWrite").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".txt_memo")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
  
